app = "locale-cartesi"

[build]
image = "registry.fly.io/locale-cartesi:latest"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "42161"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0x06f3d41f5487ba883deb055e35f28b4bdaa04257"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x5383ba03ebb2482e4907b22b06450cf85bebb314"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x9e7dab79399d7a0de20dfa6a9eb12d39decd1dbe"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "434930176"
CARTESI_EPOCH_LENGTH = "43200"
